### ISSUE TITLE
Add ability to capture from individual windows

### ISSUE THREAD

**Issue by alex-berliner** [V9X/Qshot-rs#1]
Hi there.

Is this possible currently? It would be nice to able to target particular windows instead of the entire screen for my use case.

Thanks!

**Comment by V9X** [comment]
Hello @alex-berliner , it is possible.

When you create a capture manager the first argument in the constructor is a window handle.
A window handle can be obtained using one of winapi's functions, for example, [FindWindow](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-findwindoww).

Due to the variety of possible methods to obtain the window handle I did not implement any helper function to do this and the argument itself is a plain `isize` to ensure compatibility between different winapi wrappers.

Here's an example on how to do this using the official [windows](https://crates.io/crates/windows) crate:

```rust
use windows::Win32::UI::WindowsAndMessaging::FindWindowW;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let window_handle = unsafe {
        FindWindowW(None, &windows::core::HSTRING::from("example window name"))
    };

    let manager = qshot::CaptureManager::new(
        window_handle.0, 
        (0, 0), 
        (500, 500)
    )?;

    Ok(())
}
```

**Comment by alex-berliner** [comment]
I wasn't able to get that FindWindowW code to work because of the following error, but I copied the [find_window](find_window) function from [win-screenshot](https://github.com/h04x/win-screenshot/) which uses the same function.

```
5    |         FindWindowW(None, &windows::core::HSTRING::from("example window name"))
     |         -----------       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `IntoParam<'_, PCWSTR>` is not implemented for `&HSTRING`        
     |         |
     |         required by a bound introduced by this call
```

Anyway, working more with the library now, I'm not familiar with Windows API calls and I would find it useful if there were a function that returned the image from the manager as an [image::ImageBuffer](https://docs.rs/image/latest/image/struct.ImageBuffer.html) so I don't have to work with the contents of `HBITMAP`.

Thanks again!

**Comment by V9X** [comment]
The error you're experiencing is caused by using an older version of `windows` crate.

Regarding your suggestion, the idea behind this library is to keep things as simple and efficient as possible. Conversion to `ImageBuffer` wouldn't be a big problem except for the fact that bits generated by `winapi` are in the `BGR` color type, and converting them to the `RGB` would be rather inefficient.

Yet, here's an example of how to do this:

```rust
fn main() -> Result<(), Box<dyn std::error::Error>> {
    let manager = qshot::CaptureManager::new(0, (0, 0), (500, 500))?;

    let mut bits = manager.capture()?.get_bits().to_vec();

    let mut ind = 1;
    while ind < bits.len() - 1 {
        bits.swap(ind - 1, ind + 1);
        ind += 3;
    }

    let img_buf = image::ImageBuffer::<image::Rgb<u8>, _>::from_vec(500, 500, bits).unwrap();

    Ok(())
}
```

Or you can use the [imageproc](https://crates.io/crates/imageproc) crate which probably does this kind of conversion more efficiently than I did in this example.
